# Copyright (c) 2021 Microsoft
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

train:
	python code/hello/hello.py

{% if cookiecutter.include_goodbye == "True" %}
goodbye:
	python code/goodbye/goodbye.py
{% endif %}